### ISSUE TITLE
Add documentation popup

### ISSUE THREAD

**Issue by Elsalune** [entrepreneur-interet-general/predisauvetage#112]

**Comment by AntoineAugusti** [comment]
Choses à faire figurer :
- [ ] Lien vers la documentation https://mtes-mct.github.io/secmar-documentation/
- [ ] Lien vers les données https://www.data.gouv.fr/fr/datasets/operations-coordonnees-par-les-cross/
- [ ] Lien vers GitHub https://github.com/snosan-tools/carte.snosan.fr
- [ ] Adresse de contact tech@snosan.fr
- [ ] Guide utilisateur
  - [ ] Panneau des filtres à droite
  - [ ] Visualisations à gauche
  - [ ] Zoom / Dézoom
  - [ ] Fonds de carte
  - [ ] Export de données
- [ ] Précautions d'usage
  -  [ ] Que des opérations géolocalisées
  - [ ] Ce jeu de données ne reflète ni l'accidentologie totale survenue au-delà de la bande des 300 mètres ni même l'activité globale des CROSS pour la mission de sauvetage.

**Comment by AntoineAugusti** [comment]
J'ai mis quelques idées de choses à faire figure @Elsalune. Tu peux éditer mon message pour adapter. Si tu ne veux pas tout rédiger tu peux m'assigner certains items et me ping pour que je les rédige.
