### ISSUE TITLE
Include full list of events in documentation for concerne_snosan

### ISSUE THREAD

**Issue by AntoineAugusti** [entrepreneur-interet-general/predisauvetage#124]
Follow up of #122.

The list is rather long to put it in the table. Where should it be on https://mtes-mct.github.io/secmar-documentation/ for example?

**Comment by Elsalune** [comment]
Ah oui je n'avais pas vu que signification des termes n'était pas dans la doc snosan. 
Je ne pense pas qu'il faille ajouter la colonne concerne_snosan en opendata

**Comment by AntoineAugusti** [comment]
Ça me va ! On peut écrire une nouvelle page de doc qu'on mettra à la suite.

La documentation est là : https://github.com/entrepreneur-interet-general/predisauvetage/tree/master/opendata/doc et on peut choisir quelles pages on met dans quelle version : https://github.com/snosan-tools/secmar-documentation/blob/master/.vuepress/config.js#L1-L17

**Comment by AntoineAugusti** [comment]
Done in https://github.com/entrepreneur-interet-general/predisauvetage/commit/d9d8b308ad498c27e7463ec4312b70be579d44e8
