### ISSUE TITLE
Update doc for SNOSAN filter on map

### ISSUE THREAD

**Issue by AntoineAugusti** [entrepreneur-interet-general/predisauvetage#125]

**Comment by Elsalune** [comment]
Dans signification des termes, on peut ajouter une partie concerne_snosan

**Comment by AntoineAugusti** [comment]
Cette issue concerne la carte. Ce que tu proposes est pour #124 ?

**Comment by Elsalune** [comment]
Tout à fait j'ai noté au mauvais endroit
