### ISSUE TITLE
Set a license

### ISSUE THREAD

**Issue by AntoineAugusti** [entrepreneur-interet-general/predisauvetage#3]

**Comment by AntoineAugusti** [comment]
Yeah, what you described is exactly my plan for later 👍

**Comment by bzg** [comment]
Just a gentle reminder for this issue, as the repository is quoted for its lack of license in [this comment](https://linuxfr.org/nodes/115274/comments/1749021).

**Comment by AntoineAugusti** [comment]
@bzg I've added the MIT license in https://github.com/entrepreneur-interet-general/predisauvetage/commit/63431ff9ae9af3faa87eb2afd99cc889b7d86918

Sorry it has not been done before: we had tons of things to do and we want to split his huge monorepo into smaller ones with a dedicated license for each one (MIT or Etalab license depending on the repo).

Other repos under the [predisauvetage topic](https://github.com/topics/predisauvetage) have a license already.

**Comment by bzg** [comment]
Thanks a lot for the swift action! I understand the delay, no problem at all. To add more context: I'm preparing a blog post for EIG on anything opensource-related, so I'll try to fix more issues like these in the coming weeks.
