### ISSUE TITLE
Be able to access SHOM overlay outside ministry

### ISSUE THREAD

**Issue by AntoineAugusti** [entrepreneur-interet-general/predisauvetage#5]

**Comment by benoitdavidfr** [comment]
Bonjour,
Pour régler ce problème, j'ai supprimé le contrôle d'accès aux tuiles de
https://geoapi.fr/shomgt/tile.php/gtpyr
Cette suppression pourra être maintenu si cela ne pose pas de difficulté au Shom.
Cordialement
Benoit DAVID

**Comment by AntoineAugusti** [comment]
@benoitdavidfr Super ! Est-ce que le SHOM est OK à ce sujet ?
