### ISSUE TITLE
Améliorations clusters de points

### ISSUE THREAD

**Issue by AntoineAugusti** [entrepreneur-interet-general/predisauvetage#52]
J'ai l'impression qu'actuellement les clusters sont gardés très longtemps, même quand le zoom est faible.

Voir avec des tests utilisateurs pour améliorer ça

**Comment by AntoineAugusti** [comment]
[ ] Pass from cluster to markers
[ ] Reduce marker size

**Comment by Elsalune** [comment]
Si le nombre de points est inférieur à 50 ne pas faire de markers
