### ISSUE TITLE
Create categories with wind direction to improve graphics

### ISSUE THREAD

**Issue by Elsalune** [entrepreneur-interet-general/predisauvetage#83]
Vent Nord, Nord Est, Est, Sud Est, Sud, Sud Ouest, Ouest, Nord Ouest.

**Comment by AntoineAugusti** [comment]
Je connais pas les specs, tu pourras préciser la relation entre angle et catégorie ?

**Comment by Elsalune** [comment]
pd.cut(vent_direction, bins=[0, 22.5, 67.5, 112.5, 157.5, 202.5, 247.5, 292.5, 337.5, np.inf], labels = [Nord, Nord-Est, Est, Sud-Est, Sud, Sud-Ouest, Ouest, Nord-Ouest, Nord])

**Comment by AntoineAugusti** [comment]
https://github.com/entrepreneur-interet-general/predisauvetage/commit/50408832d578466dca37db4e5e6b935f3b08987b
